# Generated by Django 2.1.5 on 2019-01-16 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelves', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.TextField(max_length=400, verbose_name='コメント'),
        ),
    ]
